Fixup/cube
SolteraGG/StickyAPI pull request #34
Opened 2020-11-28 21:14 UTC by aakatz3

Add a cube to particles

2020-11-28 21:29 UTC, aakatz3 commented
I know the particle stuff needs tests at some point, I'll do testing in stickycommands later with like a /particletool command once api is done

2021-01-22 09:30 UTC, vladfrangu requested changes

2021-01-22 09:30 UTC, vladfrangu commented on build.gradle
> +
why

2021-01-22 09:30 UTC, vladfrangu commented on build.gradle
> +apply plugin: 'org.openjfx.javafxplugin'
```suggestion
java {
    sourceCompatibility(JavaVersion.VERSION_11)
    targetCompatibility(getTargetCompatibility())
}

apply plugin: 'org.openjfx.javafxplugin'
```

2021-01-23 19:52 UTC, closed without merging