Fix & Improve ClickableSlot
SolteraGG/StickyAPI pull request #40
Opened 2020-12-05 23:42 UTC by kokumaji

* Added the ability to add lore to a ClickableSlot item 
* Fixed a NPE related to the ItemMeta

2020-12-05 23:49 UTC, vladfrangu requested changes

2020-12-05 23:49 UTC, vladfrangu commented on src/main/java/com/dumbdogdiner/stickyapi/bukkit/gui/ClickableSlot.java
> +    @Getter public ItemStack item;
Please keep this on separate lines

2020-12-05 23:49 UTC, vladfrangu commented on src/main/java/com/dumbdogdiner/stickyapi/common/util/url/URLUtil.java
> +    public static TextComponent convertURLs(String text) {
Changes unrelated to this PR..

2020-12-06 01:10 UTC, NotZachery requested changes

2020-12-06 01:10 UTC, NotZachery commented on src/main/java/com/dumbdogdiner/stickyapi/bukkit/gui/ClickableSlot.java
> +    public ClickableSlot(Material pMaterial, String pName, int pAmount, int pSlot, String... lore) {
Use `NotNull` and `Nullable` annotations for parameters please.

2020-12-06 01:10 UTC, NotZachery commented on src/main/java/com/dumbdogdiner/stickyapi/bukkit/gui/ClickableSlot.java
> +    public ClickableSlot(ItemStack item, int pSlot) {
Parameter annotations please

2020-12-06 01:10 UTC, NotZachery commented on src/main/java/com/dumbdogdiner/stickyapi/common/util/url/URLUtil.java
> +    public static TextComponent convertURLs(String text) {
Please use param annotations!

Also, this is unrelated to this PR, however I personally don't mind as long as you list it somewhere.

2020-12-06 11:48 UTC, vladfrangu requested changes

2020-12-06 11:48 UTC, vladfrangu commented on src/main/java/com/dumbdogdiner/stickyapi/bukkit/gui/ClickableSlot.java
> +    public ClickableSlot(@NotNull Material pMaterial, String pName, int pAmount, int pSlot, String... lore) {
You should reverse the name and amount, and mark the amount as NotNull either

2020-12-06 12:05 UTC, vladfrangu commented on src/main/java/com/dumbdogdiner/stickyapi/bukkit/gui/ClickableSlot.java
> +    public ClickableSlot(@NotNull ItemStack item, int pSlot) {
Missed one <3

2020-12-09 06:27 UTC, NotZachery approved these changes

2020-12-09 06:33 UTC, vladfrangu approved these changes

2020-12-09 06:33 UTC, vladfrangu commented on src/main/java/com/dumbdogdiner/stickyapi/common/util/url/URLUtil.java
> +            if((url) == null) {
```suggestion
            if(url == null) {
```

2020-12-09 17:39 UTC, merged