Rewrite the configuration package (very basic for now)
SolteraGG/StickyAPI pull request #98
Opened 2021-03-05 12:44 UTC by Prouser123

2021-03-05 13:05 UTC, kokumaji approved these changes
Maybe also add something like `YamlProvider#reload()`? Other than that, lgtm 👍 
Waiting for opinions from others

2021-03-05 14:01 UTC, SkyezerFox requested changes
Can we move this into `config`? Better integrates with future plans for a configuration module.

2021-03-05 14:01 UTC, kaylendog commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/Configuration.java
> +}
```suggestion
}

```

2021-03-12 19:50 UTC, ZachyFoxx approved these changes
LGTM

2021-03-13 10:56 UTC, SkyezerFox requested changes
LGTM, minor changes :3

2021-03-13 10:56 UTC, SkyezerFox commented on bukkit/src/main/java/com/dumbdogdiner/stickyapi/bukkit/util/StartupUtil.java
> +                YamlProvider embeddedMessagesResource = new YamlProvider(plugin.getResource("messages.en_us.yml"));
Maybe do an explicit check to see if this exists before copying it? Altho it is kinda covered by the `e.printStackTrace()` below...

2021-03-13 10:56 UTC, SkyezerFox commented on bungee/src/main/java/com/dumbdogdiner/stickyapi/bungeecord/util/StartupUtil.java
> +                YamlProvider embeddedMessagesResource = new YamlProvider(plugin.getResourceAsStream("messages.en_us.yml"));
See above.

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/FileConfiguration.java
> +package com.dumbdogdiner.stickyapi.common.configuration;
Were we not gonna move this to `stickyapi.config` module?

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/providers/YamlProvider.java
> +        // Attempt to (re)load the stream
Interesting formatting going on here - we gonna have spotless, right?
```suggestion
        // Attempt to (re)load the stream
        Yaml yaml = new Yaml();
        Map<String, Object> obj = yaml.load(this.inputStream);
        this.data = obj;
```

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/providers/YamlProvider.java
> +            save(fileWriter);
For clarity's sake
```suggestion
            this.save(fileWriter);
```

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/providers/YamlProvider.java
> +        Object value = data.get(path);
```suggestion
        Object value = this.data.get(path);
```

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/providers/YamlProvider.java
> +        Object value = data.get(path);
```suggestion
        Object value = this.data.get(path);
```

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/providers/YamlProvider.java
> +            save(fileWriter);
```suggestion
            this.save(fileWriter);
```

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/providers/YamlProvider.java
> +    private Map<String, Object> data;
Worth making this a concurrent hash map? Could potentially be accessed by different threads at the same time.

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/test/java/com/dumbdogdiner/stickyapi/common/configuration/providers/YamlProviderTest.java
> +public class YamlProviderTest {
As mentioned above, a test that forces a concurrent read/write of the config to ensure that behaves as expected.

2021-03-13 10:56 UTC, SkyezerFox commented on common/src/main/java/com/dumbdogdiner/stickyapi/common/configuration/FileConfiguration.java
> +    public void reload();
Javadoc :3

2021-03-17 21:04 UTC, merged